//! 固定 execution HTTP socket 的原生前端。
//!
//! Node/Bun 无法读取 SO_PEERCRED，因此 relay 独占公开
//! `/run/iweb-sandbox/supervisor.sock`：每个 accepted stream 都先验证 listener
//! inode、`SO_PEERCRED == Kernel 0/0`，再代理到 Node 的私有 upstream。Node 只接受
//! relay 注入的一次性进程内 token，避免私有 upstream 成为无认证的第二入口。

use iweb_kernel::wasm_snapshot_fd::{require_peer_credentials, SnapshotSocketPeer};
use std::io::Write;
use std::net::Shutdown;
use std::os::fd::AsRawFd;
use std::os::unix::net::{UnixListener, UnixStream};
use std::path::{Path, PathBuf};
use std::sync::Arc;
use std::time::Duration;

pub const EXECUTION_RELAY_AUTHORIZATION_HEADER: &str = "x-iweb-relay-authorization";
pub const EXECUTION_SOCKET_PATH_REJECTED: &str = "SUPERVISOR_SOCKET_PATH_REJECTED";
pub const EXECUTION_PEER_CREDENTIALS_REJECTED: &str = "SUPERVISOR_PEER_CREDENTIALS_REJECTED";

const MAXIMUM_REQUEST_HEADER_BYTES: usize = 16 * 1024;
const PROXY_IO_TIMEOUT: Duration = Duration::from_millis(500);

#[derive(Debug, Clone)]
pub struct ExecutionProxyConfig {
    pub public_socket: PathBuf,
    pub upstream_socket: PathBuf,
    /// A 32-byte random hex value generated by Node at startup. It never enters
    /// the Kernel-facing stream, logs, state, or an application environment.
    pub upstream_authorization: String,
    pub kernel_peer: SnapshotSocketPeer,
    pub supervisor_peer: SnapshotSocketPeer,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ExecutionProxyError {
    pub code: &'static str,
    detail: String,
}

impl ExecutionProxyError {
    fn path(detail: impl Into<String>) -> Self {
        Self {
            code: EXECUTION_SOCKET_PATH_REJECTED,
            detail: detail.into(),
        }
    }

    fn peer(detail: impl Into<String>) -> Self {
        Self {
            code: EXECUTION_PEER_CREDENTIALS_REJECTED,
            detail: detail.into(),
        }
    }
}

impl std::fmt::Display for ExecutionProxyError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(formatter, "{}: {}", self.code, self.detail)
    }
}

impl std::error::Error for ExecutionProxyError {}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
struct PathObservation {
    device: u64,
    inode: u64,
    mode: u32,
    uid: u32,
    gid: u32,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct BoundExecutionSocket {
    socket: PathObservation,
    parent: PathObservation,
}

fn lstat(path: &Path) -> Result<PathObservation, ExecutionProxyError> {
    let path = std::ffi::CString::new(path.as_os_str().as_encoded_bytes())
        .map_err(|_| ExecutionProxyError::path("execution socket path contains a NUL byte"))?;
    let mut stat: libc::stat = unsafe { std::mem::zeroed() };
    if unsafe { libc::lstat(path.as_ptr(), &mut stat) } != 0 {
        return Err(ExecutionProxyError::path(format!(
            "lstat on the execution socket path failed (errno {})",
            std::io::Error::last_os_error().raw_os_error().unwrap_or(0)
        )));
    }
    Ok(PathObservation {
        device: stat.st_dev as u64,
        inode: stat.st_ino as u64,
        mode: stat.st_mode as u32,
        uid: stat.st_uid,
        gid: stat.st_gid,
    })
}

fn validate_parent(
    path: &Path,
    expected: SnapshotSocketPeer,
) -> Result<PathObservation, ExecutionProxyError> {
    let parent = lstat(path.parent().unwrap_or_else(|| Path::new("/")))?;
    if parent.mode & libc::S_IFMT as u32 != libc::S_IFDIR as u32
        || parent.uid != expected.uid
        || parent.gid != expected.gid
        || parent.mode & 0o7777 != 0o700
    {
        return Err(ExecutionProxyError::path(
            "execution socket parent must be the supervisor-owned 0700 directory",
        ));
    }
    Ok(parent)
}

fn validate_socket(
    path: &Path,
    expected: SnapshotSocketPeer,
) -> Result<PathObservation, ExecutionProxyError> {
    let socket = lstat(path)?;
    if socket.mode & libc::S_IFMT as u32 != libc::S_IFSOCK as u32
        || socket.uid != expected.uid
        || socket.gid != expected.gid
        || socket.mode & 0o7777 != 0o600
    {
        return Err(ExecutionProxyError::path(
            "execution socket must be a supervisor-owned 0600 socket inode",
        ));
    }
    Ok(socket)
}

fn validate_bound_identity(
    path: &Path,
    expected: SnapshotSocketPeer,
    bound: BoundExecutionSocket,
) -> Result<(), ExecutionProxyError> {
    let socket = validate_socket(path, expected)?;
    let parent = validate_parent(path, expected)?;
    if socket.device != bound.socket.device
        || socket.inode != bound.socket.inode
        || parent.device != bound.parent.device
        || parent.inode != bound.parent.inode
    {
        return Err(ExecutionProxyError::path(
            "execution socket or parent inode changed after relay bind",
        ));
    }
    Ok(())
}

fn require_stream_socket(stream: &UnixStream) -> Result<(), ExecutionProxyError> {
    let mut socket_type: libc::c_int = 0;
    let mut length = std::mem::size_of::<libc::c_int>() as libc::socklen_t;
    let result = unsafe {
        libc::getsockopt(
            stream.as_raw_fd(),
            libc::SOL_SOCKET,
            libc::SO_TYPE,
            &mut socket_type as *mut libc::c_int as *mut libc::c_void,
            &mut length,
        )
    };
    if result != 0 || socket_type != libc::SOCK_STREAM {
        return Err(ExecutionProxyError::path(
            "execution relay accepted a non-stream socket",
        ));
    }
    Ok(())
}

fn is_hex_token(value: &str) -> bool {
    value.len() == 64 && value.as_bytes().iter().all(u8::is_ascii_hexdigit)
}

/// Bind the public execution listener after proving systemd's 0700 parent and
/// capture both inode identities for every subsequent accepted connection.
pub fn bind_execution_listener(
    config: &ExecutionProxyConfig,
) -> Result<(UnixListener, BoundExecutionSocket), ExecutionProxyError> {
    if !is_hex_token(&config.upstream_authorization) {
        return Err(ExecutionProxyError::peer(
            "the execution relay upstream authorization token is not a 32-byte hex value",
        ));
    }
    validate_parent(&config.public_socket, config.supervisor_peer)?;
    let _ = std::fs::remove_file(&config.public_socket);
    let listener = UnixListener::bind(&config.public_socket).map_err(|error| {
        ExecutionProxyError::path(format!(
            "bind on the fixed execution socket failed: {error}"
        ))
    })?;
    let path = std::ffi::CString::new(config.public_socket.as_os_str().as_encoded_bytes())
        .expect("the validated execution socket path contains no NUL byte");
    if unsafe { libc::chmod(path.as_ptr(), 0o600) } != 0 {
        return Err(ExecutionProxyError::path(format!(
            "chmod 0600 on the fixed execution socket failed (errno {})",
            std::io::Error::last_os_error().raw_os_error().unwrap_or(0)
        )));
    }
    let bound = BoundExecutionSocket {
        socket: validate_socket(&config.public_socket, config.supervisor_peer)?,
        parent: validate_parent(&config.public_socket, config.supervisor_peer)?,
    };
    Ok((listener, bound))
}

fn find_header_end(bytes: &[u8]) -> Option<usize> {
    bytes
        .windows(4)
        .position(|window| window == b"\r\n\r\n")
        .map(|position| position + 4)
}

/// `recvmsg` with no control buffer makes SCM_RIGHTS set MSG_CTRUNC. The relay
/// rejects that frame before forwarding any HTTP byte; the kernel discards the
/// unreceived descriptor rather than making an application-visible copy.
fn read_without_ancillary(
    stream: &UnixStream,
    bytes: &mut [u8],
) -> Result<usize, ExecutionProxyError> {
    let mut vector = libc::iovec {
        iov_base: bytes.as_mut_ptr() as *mut libc::c_void,
        iov_len: bytes.len(),
    };
    let mut message: libc::msghdr = unsafe { std::mem::zeroed() };
    message.msg_iov = &mut vector;
    message.msg_iovlen = 1;
    let read = unsafe { libc::recvmsg(stream.as_raw_fd(), &mut message, 0) };
    if read < 0 {
        return Err(ExecutionProxyError::path(format!(
            "read from the execution socket failed (errno {})",
            std::io::Error::last_os_error().raw_os_error().unwrap_or(0)
        )));
    }
    if message.msg_flags & libc::MSG_CTRUNC != 0 || message.msg_controllen != 0 {
        return Err(ExecutionProxyError::path(
            "execution HTTP rejects ancillary data before HTTP parsing",
        ));
    }
    Ok(read as usize)
}

fn read_request_prefix(stream: &UnixStream) -> Result<Vec<u8>, ExecutionProxyError> {
    stream
        .set_read_timeout(Some(PROXY_IO_TIMEOUT))
        .map_err(|error| {
            ExecutionProxyError::path(format!("set execution socket read timeout failed: {error}"))
        })?;
    let mut prefix = Vec::with_capacity(1024);
    let mut chunk = [0u8; 1024];
    loop {
        let read = read_without_ancillary(stream, &mut chunk)?;
        if read == 0 {
            return Err(ExecutionProxyError::path(
                "execution peer closed before a complete HTTP request header",
            ));
        }
        prefix.extend_from_slice(&chunk[..read]);
        if prefix.len() > MAXIMUM_REQUEST_HEADER_BYTES {
            return Err(ExecutionProxyError::path(
                "execution HTTP request header exceeds the fixed bound",
            ));
        }
        if find_header_end(&prefix).is_some() {
            return Ok(prefix);
        }
    }
}

fn header_has_relay_authorization(header: &[u8]) -> bool {
    let Ok(text) = std::str::from_utf8(header) else {
        return true;
    };
    text.split("\r\n").skip(1).any(|line| {
        line.split_once(':')
            .map(|(name, _)| name.eq_ignore_ascii_case(EXECUTION_RELAY_AUTHORIZATION_HEADER))
            .unwrap_or(false)
    })
}

fn add_relay_authorization(prefix: &[u8], token: &str) -> Result<Vec<u8>, ExecutionProxyError> {
    let header_end = find_header_end(prefix).ok_or_else(|| {
        ExecutionProxyError::path("execution relay received an incomplete HTTP request header")
    })?;
    let header = &prefix[..header_end];
    if header_has_relay_authorization(header) {
        return Err(ExecutionProxyError::peer(
            "the Kernel-facing request attempted to supply the relay authorization header",
        ));
    }
    let mut forwarded = Vec::with_capacity(
        prefix.len() + EXECUTION_RELAY_AUTHORIZATION_HEADER.len() + token.len() + 4,
    );
    forwarded.extend_from_slice(&header[..header.len() - 2]);
    forwarded.extend_from_slice(EXECUTION_RELAY_AUTHORIZATION_HEADER.as_bytes());
    forwarded.extend_from_slice(b": ");
    forwarded.extend_from_slice(token.as_bytes());
    forwarded.extend_from_slice(b"\r\n\r\n");
    forwarded.extend_from_slice(&prefix[header_end..]);
    Ok(forwarded)
}

fn proxy_authorized_connection(mut client: UnixStream, config: Arc<ExecutionProxyConfig>) {
    let prefix = match read_request_prefix(&client) {
        Ok(prefix) => prefix,
        Err(_) => return,
    };
    let request = match add_relay_authorization(&prefix, &config.upstream_authorization) {
        Ok(request) => request,
        Err(_) => return,
    };
    let mut upstream = match UnixStream::connect(&config.upstream_socket) {
        Ok(upstream) => upstream,
        Err(_) => return,
    };
    if upstream.set_write_timeout(Some(PROXY_IO_TIMEOUT)).is_err()
        || upstream.write_all(&request).is_err()
    {
        return;
    }
    let Ok(mut client_to_upstream) = client.try_clone() else {
        return;
    };
    let Ok(mut upstream_writer) = upstream.try_clone() else {
        return;
    };
    let forward = std::thread::spawn(move || {
        let _ = std::io::copy(&mut client_to_upstream, &mut upstream_writer);
        let _ = upstream_writer.shutdown(Shutdown::Write);
    });
    let _ = std::io::copy(&mut upstream, &mut client);
    let _ = client.shutdown(Shutdown::Write);
    let _ = forward.join();
}

/// Accept loop for the only Kernel-visible execution socket. A rejected peer is
/// closed before the relay reads an HTTP header or opens the Node upstream.
pub fn run_execution_proxy(
    listener: UnixListener,
    config: Arc<ExecutionProxyConfig>,
    bound: BoundExecutionSocket,
) {
    for connection in listener.incoming() {
        let Ok(stream) = connection else {
            continue;
        };
        if validate_bound_identity(&config.public_socket, config.supervisor_peer, bound).is_err()
            || require_stream_socket(&stream).is_err()
            || require_peer_credentials(&stream, &config.kernel_peer).is_err()
            || validate_bound_identity(&config.public_socket, config.supervisor_peer, bound)
                .is_err()
        {
            continue;
        }
        let connection_config = Arc::clone(&config);
        let _ = std::thread::Builder::new()
            .name("iweb-execution-http-proxy".to_string())
            .spawn(move || proxy_authorized_connection(stream, connection_config));
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn relay_authorization_is_injected_and_caller_supplied_headers_are_rejected() {
        let prefix = b"POST /v1/execution-rpc HTTP/1.1\r\nHost: iweb-supervisor\r\nContent-Length: 2\r\n\r\n{}";
        let token = "a".repeat(64);
        let forwarded =
            add_relay_authorization(prefix, &token).expect("relay must inject its own header");
        let text = String::from_utf8(forwarded).expect("forwarded HTTP is utf8");
        assert!(text.contains("x-iweb-relay-authorization: "));
        assert!(text.ends_with("\r\n\r\n{}"));
        let supplied = b"GET /v1/health HTTP/1.1\r\nx-iweb-relay-authorization: forged\r\n\r\n";
        assert_eq!(
            add_relay_authorization(supplied, &token).unwrap_err().code,
            EXECUTION_PEER_CREDENTIALS_REJECTED
        );
    }

    #[test]
    fn relay_token_is_fixed_size_hex() {
        assert!(is_hex_token(&"f".repeat(64)));
        assert!(!is_hex_token("not-a-token"));
        assert!(!is_hex_token(&"g".repeat(64)));
    }
}
